version: '3'
services:
  database:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: Minnu@123
     MYSQL_DATABASE: employee
    ports:
    - "1433:3306"
    
  employeeservice:
    image: e1
    container_name: employee-container
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    depends_on:
    - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/employee?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Minnu@123
    
     
   
   
   